In [45]:
import pandas as pd
d=pd.read_csv('/content/garments_worker_productivity.csv')
print(d)

           date   quarter  department        day  team  targeted_productivity  \
0      1/1/2015  Quarter1      sweing   Thursday     8                   0.80
1      1/1/2015  Quarter1  finishing    Thursday     1                   0.75
2      1/1/2015  Quarter1      sweing   Thursday    11                   0.80
3      1/1/2015  Quarter1      sweing   Thursday    12                   0.80
4      1/1/2015  Quarter1      sweing   Thursday     6                   0.80
...         ...       ...         ...        ...   ...                    ...
1192  3/11/2015  Quarter2   finishing  Wednesday    10                   0.75
1193  3/11/2015  Quarter2   finishing  Wednesday     8                   0.70
1194  3/11/2015  Quarter2   finishing  Wednesday     7                   0.65
1195  3/11/2015  Quarter2   finishing  Wednesday     9                   0.75
1196  3/11/2015  Quarter2   finishing  Wednesday     6                   0.70

        smv     wip  over_time  incentive  idle_time  idle_men  \
0     26.16  1108.0       7080         98        0.0         0
1      3.94     NaN        960          0        0.0         0
2     11.41   968.0       3660         50        0.0         0
3     11.41   968.0       3660         50        0.0         0
4     25.90  1170.0       1920         50        0.0         0
...     ...     ...        ...        ...        ...       ...
1192   2.90     NaN        960          0        0.0         0
1193   3.90     NaN        960          0        0.0         0
1194   3.90     NaN        960          0        0.0         0
1195   2.90     NaN       1800          0        0.0         0
1196   2.90     NaN        720          0        0.0         0

      no_of_style_change  no_of_workers  actual_productivity
0                      0           59.0             0.940725
1                      0            8.0             0.886500
2                      0           30.5             0.800570
3                      0           30.5             0.800570
4                      0           56.0             0.800382
...                  ...            ...                  ...
1192                   0            8.0             0.628333
1193                   0            8.0             0.625625
1194                   0            8.0             0.625625
1195                   0           15.0             0.505889
1196                   0            6.0             0.394722

[1197 rows x 15 columns]

In [49]:
x1=d['team']
x2=d['targeted_productivity']
x3=d['smv']
x4=d['wip']
x5=d['over_time']
x6=d['incentive']
x7=d['idle_time']
x8=d['idle_men']
x9=d['no_of_style_change']
x10=d['no_of_workers']
y=d['targeted_productivity']
print(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,y)
x4=x4.fillna(0)
print(x4)
import random
x1_train=[]
x2_train=[]
x3_train=[]
x4_train=[]
x5_train=[]
x6_train=[]
x7_train=[]
x8_train=[]
x9_train=[]
x10_train=[]
y_train=[]

0        8
1        1
2       11
3       12
4        6
        ..
1192    10
1193     8
1194     7
1195     9
1196     6
Name: team, Length: 1197, dtype: int64 0       0.80
1       0.75
2       0.80
3       0.80
4       0.80
        ...
1192    0.75
1193    0.70
1194    0.65
1195    0.75
1196    0.70
Name: targeted_productivity, Length: 1197, dtype: float64 0       26.16
1        3.94
2       11.41
3       11.41
4       25.90
        ...
1192     2.90
1193     3.90
1194     3.90
1195     2.90
1196     2.90
Name: smv, Length: 1197, dtype: float64 0       1108.0
1          NaN
2        968.0
3        968.0
4       1170.0
         ...
1192       NaN
1193       NaN
1194       NaN
1195       NaN
1196       NaN
Name: wip, Length: 1197, dtype: float64 0       7080
1        960
2       3660
3       3660
4       1920
        ...
1192     960
1193     960
1194     960
1195    1800
1196     720
Name: over_time, Length: 1197, dtype: int64 0       98
1        0
2       50
3       50
4       50
        ..
1192     0
1193     0
1194     0
1195     0
1196     0
Name: incentive, Length: 1197, dtype: int64 0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
1192    0.0
1193    0.0
1194    0.0
1195    0.0
1196    0.0
Name: idle_time, Length: 1197, dtype: float64 0       0
1       0
2       0
3       0
4       0
       ..
1192    0
1193    0
1194    0
1195    0
1196    0
Name: idle_men, Length: 1197, dtype: int64 0       0
1       0
2       0
3       0
4       0
       ..
1192    0
1193    0
1194    0
1195    0
1196    0
Name: no_of_style_change, Length: 1197, dtype: int64 0       59.0
1        8.0
2       30.5
3       30.5
4       56.0
        ...
1192     8.0
1193     8.0
1194     8.0
1195    15.0
1196     6.0
Name: no_of_workers, Length: 1197, dtype: float64 0       0.80
1       0.75
2       0.80
3       0.80
4       0.80
        ...
1192    0.75
1193    0.70
1194    0.65
1195    0.75
1196    0.70
Name: targeted_productivity, Length: 1197, dtype: float64
0       1108.0
1          0.0
2        968.0
3        968.0
4       1170.0
         ...
1192       0.0
1193       0.0
1194       0.0
1195       0.0
1196       0.0
Name: wip, Length: 1197, dtype: float64

In [50]:
for j in range(0,800):
  for i in range(0,1197,2):
    x1_train.append(x1[i])
    x2_train.append(x2[i])
    x3_train.append(x3[i])
    x4_train.append(x4[i])
    x5_train.append(x5[i])
    x6_train.append(x6[i])
    x7_train.append(x7[i])
    x8_train.append(x8[i])
    x9_train.append(x9[i])
    x10_train.append(x10[i])
    y_train.append(y[i])

In [51]:
x1_test=[]
x2_test=[]
x3_test=[]
x4_test=[]
x5_test=[]
x6_test=[]
x7_test=[]
x8_test=[]
x9_test=[]
x10_test=[]
y_test=[]
for i in range(801,1197):
  for i in range(0,1197,2):
    x1_test.append(x1[i])
    x2_test.append(x2[i])
    x3_test.append(x3[i])
    x4_test.append(x4[i])
    x5_test.append(x5[i])
    x6_test.append(x6[i])
    x7_test.append(x7[i])
    x8_test.append(x8[i])
    x9_test.append(x9[i])
    x10_test.append(x10[i])
    y_test.append(y[i])
import numpy as np

In [62]:
e=[]
ee=[]
def linear(m,m1,m2,m3,m4,m5,m6,m7,m8,m9,c):
  sum=0
  yp=[]
  for i in range(0,len(x10_train)):
    yp.append(m*x1_train[i]+m1*x2_train[i]+m2*x3_train[i]+m3*x4_train[i]+m4*x5_train[i]+m5*x6_train[i]+m6*x7_train[i]+m7*x8_train[i]+m8*x9_train[i]+m9*x10_train[i]+c)
    g=(y_train[i]-yp[i])**2
    sum=sum+g
    e.append(sum)
    ee.append(np.mod(sum,len(x1_train)))
    print(m,m1,m2,m3,m4,m5,m6,m7,m8,m9,c,np.mod(sum,len(x10_train)))
    sum=0
    for i in range(1,1):
      linear(1+i,2+i,3+i,4+i,5+i,6+i,7+i,8+i,9+i,10+i,11+i)
      print(ee)
      a=np.array(ee).min()
      print(a)
      c=np.where(ee==a)
      print(c)
      ee1=np.arange(0,99)
      print(ee1)

In [69]:
import numpy as np
z=[]
zz=[]
def linear1(m,m1,m2,m3,m4,m5,m6,m7,m8,m9,c):
  sum=0
  yp=[]
  j=0
  for i in range(801,1196):
    yp.append(m*x1_test[i]+m1*x2_test[i]+m2*x3_test[i]+m3*x4_test[i]+m4*x5_test[i]+m5*x6_test[i]+m6*x7_test[i]+m7*x8_test[i]+m8*x9_test[i]+m9*x10_test[i]+c)
    g=(y_test[i]-yp[j])**2
    j=j+1
    sum=sum+g
    z.append(sum)
    zz.append(np.mod(sum,len(x1_test)))
    print(m,m1,m2,m3,m4,m5,m6,m7,m8,m9,c,np.mod(sum,len(x1_test)))
    linear1(19, 20 ,21, 22, 23, 24, 25, 26, 27 ,28 ,29)
    from matplotlib import pyplot as pp
    pp.plot(ee1,ee)